name: Main
on: [push, pull_request]
jobs:

  tests:
    name: ${{matrix.go-version}} ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: ['stable']
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - os: ubuntu-latest
            go-version: ''

    steps:
    - name: Install dependencies (linux)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt-get update && sudo apt-get install libgl1-mesa-dev

    - name: Check out module
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{matrix.go-version}}
        go-version-file: go.mod

    - name: Run tests
      run: go test -v -race ./...
